repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.6
    hooks:
      - id: ruff
        args: [--select, I, --fix]
        files: ^retrieve/
      - id: ruff-format
        files: ^retrieve/
