# Written by `eval-data ingest laion30m` (eval_datasets/ingest.py). Clauses, in order: C0 domain, C1 size, C2 similarity, C3 domain_reverse (reverse), C4 watermark, C5 unsafe.
data_dir: data/laion30m
content_dir: content_d256
dims: [256]
users_limit: 10000
filters:
  attrs: item_attrs_narrow.pt
  reverse: clause_is_reverse_narrow.pt
  clause:
    c0_domain: [0]
    c3_domain_reverse: [3]
    tags4: [1, 2, 4, 5]
    all_fwd: [0, 1, 2, 4, 5]
  bloom:
    c0_domain: [0]
    tags4: [1, 2, 4, 5]
    all_fwd: [0, 1, 2, 4, 5]
